services:
  postgres:
    image: postgres:15-alpine
    container_name: career-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: white-carrot

  backend:
    build: ./career-page-builder-be
    container_name: career-be
    env_file:
      - ./career-page-builder-be/.env
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    command: npm run dev

  frontend:
    build: ./career-page-builder-fe
    container_name: career-fe
    depends_on:
      - backend
    ports:
      - "3000:3000"
    command: npm run dev
